# Generated by Django 2.0.4 on 2018-11-19 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'hazard_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HazardReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('title_text', models.CharField(max_length=45)),
                ('content_text', models.TextField()),
                ('zipcode', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard.Category')),
            ],
        ),
        migrations.CreateModel(
            name='HazardReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('content_text', models.TextField()),
                ('hazardreport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hazard.HazardReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hazard.Status'),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazardposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
